export const CHANGE_CONSOLE = 'CHANGE_CONSOLE';

export const UPDATE_USER = 'UPDATE_USER';

export const UPDATE_MOBILE_NUMBER = 'UPDATE_MOBILE_NUMBER';

export const UPDATE_DEVICE_TOKEN = 'UPDATE_DEVICE_TOKEN';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const UPDATE_PROVIDER = 'UPDATE_PROVIDER';

export const SELECT_BILL = 'SELECT_BILL';

export const UPDATE_BILL_INFO = 'UPDATE_BILL_INFO';

export const UPDATE_BARCODE_INFO = 'UPDATE_BARCODE_INFO';

